// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: internal/event/event.proto

package event

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	player "mafia-grpc/internal/player"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameEndEvent_Team int32

const (
	GameEndEvent_Red   GameEndEvent_Team = 0
	GameEndEvent_Black GameEndEvent_Team = 1
)

// Enum value maps for GameEndEvent_Team.
var (
	GameEndEvent_Team_name = map[int32]string{
		0: "Red",
		1: "Black",
	}
	GameEndEvent_Team_value = map[string]int32{
		"Red":   0,
		"Black": 1,
	}
)

func (x GameEndEvent_Team) Enum() *GameEndEvent_Team {
	p := new(GameEndEvent_Team)
	*p = x
	return p
}

func (x GameEndEvent_Team) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameEndEvent_Team) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_event_event_proto_enumTypes[0].Descriptor()
}

func (GameEndEvent_Team) Type() protoreflect.EnumType {
	return &file_internal_event_event_proto_enumTypes[0]
}

func (x GameEndEvent_Team) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameEndEvent_Team.Descriptor instead.
func (GameEndEvent_Team) EnumDescriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{8, 0}
}

type JoinEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *player.Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *JoinEvent) Reset() {
	*x = JoinEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinEvent) ProtoMessage() {}

func (x *JoinEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinEvent.ProtoReflect.Descriptor instead.
func (*JoinEvent) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{0}
}

func (x *JoinEvent) GetPlayer() *player.Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type LeftEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *player.Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *LeftEvent) Reset() {
	*x = LeftEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeftEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeftEvent) ProtoMessage() {}

func (x *LeftEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeftEvent.ProtoReflect.Descriptor instead.
func (*LeftEvent) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{1}
}

func (x *LeftEvent) GetPlayer() *player.Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type MessageEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{2}
}

func (x *MessageEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartDayEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KilledPlayer *player.Player `protobuf:"bytes,1,opt,name=killed_player,json=killedPlayer,proto3" json:"killed_player,omitempty"`
}

func (x *StartDayEvent) Reset() {
	*x = StartDayEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartDayEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDayEvent) ProtoMessage() {}

func (x *StartDayEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDayEvent.ProtoReflect.Descriptor instead.
func (*StartDayEvent) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{3}
}

func (x *StartDayEvent) GetKilledPlayer() *player.Player {
	if x != nil {
		return x.KilledPlayer
	}
	return nil
}

type StartNightEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KilledPlayer *player.Player `protobuf:"bytes,1,opt,name=killed_player,json=killedPlayer,proto3" json:"killed_player,omitempty"`
}

func (x *StartNightEvent) Reset() {
	*x = StartNightEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartNightEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartNightEvent) ProtoMessage() {}

func (x *StartNightEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartNightEvent.ProtoReflect.Descriptor instead.
func (*StartNightEvent) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{4}
}

func (x *StartNightEvent) GetKilledPlayer() *player.Player {
	if x != nil {
		return x.KilledPlayer
	}
	return nil
}

type VoteEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requester *player.Player `protobuf:"bytes,1,opt,name=requester,proto3" json:"requester,omitempty"`
	Vote      *player.Player `protobuf:"bytes,2,opt,name=vote,proto3" json:"vote,omitempty"`
}

func (x *VoteEvent) Reset() {
	*x = VoteEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteEvent) ProtoMessage() {}

func (x *VoteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteEvent.ProtoReflect.Descriptor instead.
func (*VoteEvent) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{5}
}

func (x *VoteEvent) GetRequester() *player.Player {
	if x != nil {
		return x.Requester
	}
	return nil
}

func (x *VoteEvent) GetVote() *player.Player {
	if x != nil {
		return x.Vote
	}
	return nil
}

type RepeatVotingEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attempt int32 `protobuf:"varint,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
}

func (x *RepeatVotingEvent) Reset() {
	*x = RepeatVotingEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepeatVotingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatVotingEvent) ProtoMessage() {}

func (x *RepeatVotingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatVotingEvent.ProtoReflect.Descriptor instead.
func (*RepeatVotingEvent) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{6}
}

func (x *RepeatVotingEvent) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type RevealedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Player *player.Player `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
}

func (x *RevealedEvent) Reset() {
	*x = RevealedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RevealedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevealedEvent) ProtoMessage() {}

func (x *RevealedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevealedEvent.ProtoReflect.Descriptor instead.
func (*RevealedEvent) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{7}
}

func (x *RevealedEvent) GetPlayer() *player.Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type GameEndEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team GameEndEvent_Team `protobuf:"varint,1,opt,name=team,proto3,enum=event.GameEndEvent_Team" json:"team,omitempty"`
}

func (x *GameEndEvent) Reset() {
	*x = GameEndEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameEndEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameEndEvent) ProtoMessage() {}

func (x *GameEndEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameEndEvent.ProtoReflect.Descriptor instead.
func (*GameEndEvent) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{8}
}

func (x *GameEndEvent) GetTeam() GameEndEvent_Team {
	if x != nil {
		return x.Team
	}
	return GameEndEvent_Red
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*Event_JoinEvent
	//	*Event_LeftEvent
	//	*Event_StartDayEvent
	//	*Event_StartNightEvent
	//	*Event_VoteEvent
	//	*Event_RepeatVotingEvent
	//	*Event_RevealedEvent
	//	*Event_GameEndEvent
	Event isEvent_Event `protobuf_oneof:"event"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_event_event_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_event_event_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_event_event_proto_rawDescGZIP(), []int{9}
}

func (m *Event) GetEvent() isEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *Event) GetJoinEvent() *JoinEvent {
	if x, ok := x.GetEvent().(*Event_JoinEvent); ok {
		return x.JoinEvent
	}
	return nil
}

func (x *Event) GetLeftEvent() *LeftEvent {
	if x, ok := x.GetEvent().(*Event_LeftEvent); ok {
		return x.LeftEvent
	}
	return nil
}

func (x *Event) GetStartDayEvent() *StartDayEvent {
	if x, ok := x.GetEvent().(*Event_StartDayEvent); ok {
		return x.StartDayEvent
	}
	return nil
}

func (x *Event) GetStartNightEvent() *StartNightEvent {
	if x, ok := x.GetEvent().(*Event_StartNightEvent); ok {
		return x.StartNightEvent
	}
	return nil
}

func (x *Event) GetVoteEvent() *VoteEvent {
	if x, ok := x.GetEvent().(*Event_VoteEvent); ok {
		return x.VoteEvent
	}
	return nil
}

func (x *Event) GetRepeatVotingEvent() *RepeatVotingEvent {
	if x, ok := x.GetEvent().(*Event_RepeatVotingEvent); ok {
		return x.RepeatVotingEvent
	}
	return nil
}

func (x *Event) GetRevealedEvent() *RevealedEvent {
	if x, ok := x.GetEvent().(*Event_RevealedEvent); ok {
		return x.RevealedEvent
	}
	return nil
}

func (x *Event) GetGameEndEvent() *GameEndEvent {
	if x, ok := x.GetEvent().(*Event_GameEndEvent); ok {
		return x.GameEndEvent
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_JoinEvent struct {
	JoinEvent *JoinEvent `protobuf:"bytes,1,opt,name=join_event,json=joinEvent,proto3,oneof"`
}

type Event_LeftEvent struct {
	LeftEvent *LeftEvent `protobuf:"bytes,2,opt,name=left_event,json=leftEvent,proto3,oneof"`
}

type Event_StartDayEvent struct {
	StartDayEvent *StartDayEvent `protobuf:"bytes,3,opt,name=start_day_event,json=startDayEvent,proto3,oneof"`
}

type Event_StartNightEvent struct {
	StartNightEvent *StartNightEvent `protobuf:"bytes,4,opt,name=start_night_event,json=startNightEvent,proto3,oneof"`
}

type Event_VoteEvent struct {
	VoteEvent *VoteEvent `protobuf:"bytes,5,opt,name=vote_event,json=voteEvent,proto3,oneof"`
}

type Event_RepeatVotingEvent struct {
	RepeatVotingEvent *RepeatVotingEvent `protobuf:"bytes,6,opt,name=repeat_voting_event,json=repeatVotingEvent,proto3,oneof"`
}

type Event_RevealedEvent struct {
	RevealedEvent *RevealedEvent `protobuf:"bytes,7,opt,name=revealed_event,json=revealedEvent,proto3,oneof"`
}

type Event_GameEndEvent struct {
	GameEndEvent *GameEndEvent `protobuf:"bytes,8,opt,name=game_end_event,json=gameEndEvent,proto3,oneof"`
}

func (*Event_JoinEvent) isEvent_Event() {}

func (*Event_LeftEvent) isEvent_Event() {}

func (*Event_StartDayEvent) isEvent_Event() {}

func (*Event_StartNightEvent) isEvent_Event() {}

func (*Event_VoteEvent) isEvent_Event() {}

func (*Event_RepeatVotingEvent) isEvent_Event() {}

func (*Event_RevealedEvent) isEvent_Event() {}

func (*Event_GameEndEvent) isEvent_Event() {}

var File_internal_event_event_proto protoreflect.FileDescriptor

var file_internal_event_event_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x1a, 0x1c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x33, 0x0a, 0x09, 0x4a, 0x6f, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x26,
	0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x33, 0x0a, 0x09, 0x4c, 0x65, 0x66, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x0c, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x44, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61,
	0x79, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x0d, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64,
	0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0c, 0x6b,
	0x69, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x46, 0x0a, 0x0f, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x4e, 0x69, 0x67, 0x68, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x33,
	0x0a, 0x0d, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x0c, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x22, 0x5d, 0x0a, 0x09, 0x56, 0x6f, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x2c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x12, 0x22,
	0x0a, 0x04, 0x76, 0x6f, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x04, 0x76, 0x6f,
	0x74, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x56, 0x6f, 0x74, 0x69,
	0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d,
	0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70,
	0x74, 0x22, 0x37, 0x0a, 0x0d, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x12, 0x26, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x58, 0x0a, 0x0c, 0x47, 0x61,
	0x6d, 0x65, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x65,
	0x61, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x54, 0x65,
	0x61, 0x6d, 0x52, 0x04, 0x74, 0x65, 0x61, 0x6d, 0x22, 0x1a, 0x0a, 0x04, 0x54, 0x65, 0x61, 0x6d,
	0x12, 0x07, 0x0a, 0x03, 0x52, 0x65, 0x64, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x6c, 0x61,
	0x63, 0x6b, 0x10, 0x01, 0x22, 0xf7, 0x03, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x31,
	0x0a, 0x0a, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6a, 0x6f, 0x69, 0x6e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x12, 0x31, 0x0a, 0x0a, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4c, 0x65,
	0x66, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x65, 0x66, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x64, 0x61,
	0x79, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x79, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x79, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x44, 0x0a, 0x11, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6e, 0x69,
	0x67, 0x68, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4e, 0x69, 0x67,
	0x68, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x4e, 0x69, 0x67, 0x68, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x76, 0x6f,
	0x74, 0x65, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x56, 0x6f, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x09, 0x76, 0x6f, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x4a, 0x0a,
	0x13, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x5f, 0x76, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x2e, 0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x56, 0x6f, 0x74, 0x69, 0x6e, 0x67, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x11, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x56, 0x6f,
	0x74, 0x69, 0x6e, 0x67, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x0e, 0x72, 0x65, 0x76,
	0x65, 0x61, 0x6c, 0x65, 0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x76, 0x65, 0x61, 0x6c,
	0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x65, 0x76, 0x65, 0x61,
	0x6c, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3b, 0x0a, 0x0e, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x65, 0x6e, 0x64, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x45, 0x6e, 0x64,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x42, 0x1b,
	0x5a, 0x19, 0x6d, 0x61, 0x66, 0x69, 0x61, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_event_event_proto_rawDescOnce sync.Once
	file_internal_event_event_proto_rawDescData = file_internal_event_event_proto_rawDesc
)

func file_internal_event_event_proto_rawDescGZIP() []byte {
	file_internal_event_event_proto_rawDescOnce.Do(func() {
		file_internal_event_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_event_event_proto_rawDescData)
	})
	return file_internal_event_event_proto_rawDescData
}

var file_internal_event_event_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_event_event_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_event_event_proto_goTypes = []interface{}{
	(GameEndEvent_Team)(0),    // 0: event.GameEndEvent.Team
	(*JoinEvent)(nil),         // 1: event.JoinEvent
	(*LeftEvent)(nil),         // 2: event.LeftEvent
	(*MessageEvent)(nil),      // 3: event.MessageEvent
	(*StartDayEvent)(nil),     // 4: event.StartDayEvent
	(*StartNightEvent)(nil),   // 5: event.StartNightEvent
	(*VoteEvent)(nil),         // 6: event.VoteEvent
	(*RepeatVotingEvent)(nil), // 7: event.RepeatVotingEvent
	(*RevealedEvent)(nil),     // 8: event.RevealedEvent
	(*GameEndEvent)(nil),      // 9: event.GameEndEvent
	(*Event)(nil),             // 10: event.Event
	(*player.Player)(nil),     // 11: player.Player
}
var file_internal_event_event_proto_depIdxs = []int32{
	11, // 0: event.JoinEvent.player:type_name -> player.Player
	11, // 1: event.LeftEvent.player:type_name -> player.Player
	11, // 2: event.StartDayEvent.killed_player:type_name -> player.Player
	11, // 3: event.StartNightEvent.killed_player:type_name -> player.Player
	11, // 4: event.VoteEvent.requester:type_name -> player.Player
	11, // 5: event.VoteEvent.vote:type_name -> player.Player
	11, // 6: event.RevealedEvent.player:type_name -> player.Player
	0,  // 7: event.GameEndEvent.team:type_name -> event.GameEndEvent.Team
	1,  // 8: event.Event.join_event:type_name -> event.JoinEvent
	2,  // 9: event.Event.left_event:type_name -> event.LeftEvent
	4,  // 10: event.Event.start_day_event:type_name -> event.StartDayEvent
	5,  // 11: event.Event.start_night_event:type_name -> event.StartNightEvent
	6,  // 12: event.Event.vote_event:type_name -> event.VoteEvent
	7,  // 13: event.Event.repeat_voting_event:type_name -> event.RepeatVotingEvent
	8,  // 14: event.Event.revealed_event:type_name -> event.RevealedEvent
	9,  // 15: event.Event.game_end_event:type_name -> event.GameEndEvent
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_internal_event_event_proto_init() }
func file_internal_event_event_proto_init() {
	if File_internal_event_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_event_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_event_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeftEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_event_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_event_event_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartDayEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_event_event_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartNightEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_event_event_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_event_event_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepeatVotingEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_event_event_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RevealedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_event_event_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameEndEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_event_event_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_event_event_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*Event_JoinEvent)(nil),
		(*Event_LeftEvent)(nil),
		(*Event_StartDayEvent)(nil),
		(*Event_StartNightEvent)(nil),
		(*Event_VoteEvent)(nil),
		(*Event_RepeatVotingEvent)(nil),
		(*Event_RevealedEvent)(nil),
		(*Event_GameEndEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_event_event_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_event_event_proto_goTypes,
		DependencyIndexes: file_internal_event_event_proto_depIdxs,
		EnumInfos:         file_internal_event_event_proto_enumTypes,
		MessageInfos:      file_internal_event_event_proto_msgTypes,
	}.Build()
	File_internal_event_event_proto = out.File
	file_internal_event_event_proto_rawDesc = nil
	file_internal_event_event_proto_goTypes = nil
	file_internal_event_event_proto_depIdxs = nil
}
